### ISSUE TITLE
how is the 'callback_urls' parameter used?

### ISSUE THREAD

**Issue by imosquera** [simplegeo/python-simplegeo#10]
In the models.py there is a Layer model with the init method signature:

def **init**(self, name, title='', description='', public=False,
                 callback_urls=[]):

what/how are the callback_urls used within the python client libraries?  

an example would be great.  thanks.

**Comment by aguynamedben** [comment]
imosquera,

This is remnant of an old, undocumented feature that may reappear in the future.  At the layer level, you could give a list of callback URLs.  When your record made it through our queues and was ready to appear in results (normally takes less than a second), an HTTP PUT request would be sent to the layer's callback URLs.  When a record was deleted and confirmed deleted, an HTTP DELETE request would be sent to the URL.  The body of the requests would be the GeoJSON formatted record.

This undocumented feature should work "in theory", but we currently do not support it at all, and there is no documentation for it.  Feel free to give it a try, but no guarantees.

-Ben Standefer
